// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Divide(arg1:number,arg2:number):Promise<number>;

export function GetUser(arg1:number):Promise<domain.User>;

export function Greet(arg1:string):Promise<string>;

export function ListUsers(arg1:number):Promise<Array<domain.User>>;
