// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Divide(arg1, arg2) {
  return window['go']['main']['App']['Divide'](arg1, arg2);
}

export function GetUser(arg1) {
  return window['go']['main']['App']['GetUser'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListUsers(arg1) {
  return window['go']['main']['App']['ListUsers'](arg1);
}
